version: '3'

services:
  worker1:
    command: ["/bin/sh", "-c", "./go/bin/worker & ./go/bin/localobjstore & ./go/bin/localscheduler & sleep 2 && python3 scripts/fig8a.py 1 & sleep infinity"]
    depends_on:
      - worker2
      - worker3
      - gcs
      - global_scheduler

#  worker2:
#    command: ["/bin/sh", "-c", "./go/bin/localscheduler & ./go/bin/localobjstore & ./go/bin/worker"]
#
#  worker3:
#    command: ["/bin/sh", "-c", "./go/bin/localscheduler & ./go/bin/localobjstore & ./go/bin/worker"]

