version: '3'

services:
  worker1:
    command: ["/bin/sh", "-c", "python3 -u -m pythonserver.worker & ./go/bin/localobjstore & ./go/bin/localscheduler & sleep 5 && python3 -u scripts/fig9.py & sleep infinity"]
    depends_on:
      # - zookeeper
      - worker2
      - worker3
      - gcs
      - global_scheduler
