version: '3'

services:
  worker1:
  # -u for the python script to flush output immediately
    command: ["/bin/sh", "-c", "python3 -u -m pythonserver.worker & ./go/bin/localobjstore & ./go/bin/localscheduler & sleep 5 && python3 -u scripts/fig11.py & sleep infinity"]
    depends_on:
      # - zookeeper
      - worker2
      - worker3
      - gcs
      - global_scheduler
