version: '3'

services:
  # zookeeper:
  #   image: zookeeper:3.6.3
  #   ports:
  #     - "2181:2181"
  #   networks:
  #     mynetwork:

  gcs:
    image: ray-node:base
    command: ["/bin/sh", "-c", "./go/bin/gcsfunctable & ./go/bin/gcsobjtable"]
    networks:
        mynetwork:
            aliases:
                - node0
    # depends_on:
    #   - zookeeper
    ports:
      - "50000:50000"

  global_scheduler:
    image: ray-node:base
    command: ["/bin/sh", "-c", "./go/bin/globalscheduler"]
    networks:
        mynetwork:
            aliases:
                - node1
    ports:
      - "50001:50001"
    environment:
        LOCALITY_AWARE: "true"

  worker1:
    image: ray-node:driver
    command: ["/bin/sh", "-c", "python3 -u -m pythonserver.worker & ./go/bin/localobjstore & ./go/bin/localscheduler & sleep infinity"]
    networks:
        mynetwork:
            aliases:
                - node2
    # depends_on:
    #   - zookeeper
    shm_size: '4g'
    ports:
      - "50002:50002"
    environment:
      NODE_ID: 2

  worker2:
    image: ray-node:driver
    command: ["/bin/sh", "-c", "python3 -u -m pythonserver.worker & ./go/bin/localobjstore & ./go/bin/localscheduler & sleep infinity"]
    networks:
        mynetwork:
            aliases:
                - node3
    # depends_on:
    #   - zookeeper
    shm_size: '4g'
    ports:
      - "50003:50003"
    environment:
      NODE_ID: 3

  worker3:
    image: ray-node:driver
    command: ["/bin/sh", "-c", "python3 -u -m pythonserver.worker & ./go/bin/localobjstore & ./go/bin/localscheduler & sleep infinity"]
    #command: ["/bin/sh", "-c", "./go/bin/localscheduler & ./go/bin/localobjstore & ./go/bin/worker"]
    networks:
        mynetwork:
            aliases:
                - node4
    # depends_on:
    #   - zookeeper
    shm_size: '4g'
    ports:
      - "50004:50004"
    environment:
      NODE_ID: 4

networks:
    mynetwork:
        driver: bridge
