version: '3'

services:
  gcs:
    image: ray-node
    command: ["/bin/sh", "-c", "./go/bin/gcsfunctable & ./go/bin/gcsobjtable"]
    ports:
      - "50000:50000"

  global_scheduler:
    image: ray-node
    command: ["/bin/sh", "-c", "./go/bin/globalscheduler &"]
    ports:
      - "50001:50001"

  worker1:
    image: ray-node
    command: ["/bin/sh", "-c", "./go/bin/localscheduler & ./go/bin/localobjstore"]
    ports:
      - "50002:50002"

  worker2:
    image: ray-node
    command: ["/bin/sh", "-c", "./go/bin/localscheduler & ./go/bin/localobjstore"]
    ports:
      - "50003:50003"

  worker3:
    image: ray-node
    command: ["/bin/sh", "-c", "./go/bin/localscheduler & ./go/bin/localobjstore"]
    ports:
      - "50004:50004"

