// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.1
// source: rayclient.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RayDriver_ExecuteCommand_FullMethodName = "/ray.RayDriver/ExecuteCommand"
)

// RayDriverClient is the client API for RayDriver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RayDriverClient interface {
	ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
}

type rayDriverClient struct {
	cc grpc.ClientConnInterface
}

func NewRayDriverClient(cc grpc.ClientConnInterface) RayDriverClient {
	return &rayDriverClient{cc}
}

func (c *rayDriverClient) ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, RayDriver_ExecuteCommand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RayDriverServer is the server API for RayDriver service.
// All implementations must embed UnimplementedRayDriverServer
// for forward compatibility
type RayDriverServer interface {
	ExecuteCommand(context.Context, *CommandRequest) (*CommandResponse, error)
	mustEmbedUnimplementedRayDriverServer()
}

// UnimplementedRayDriverServer must be embedded to have forward compatible implementations.
type UnimplementedRayDriverServer struct {
}

func (UnimplementedRayDriverServer) ExecuteCommand(context.Context, *CommandRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedRayDriverServer) mustEmbedUnimplementedRayDriverServer() {}

// UnsafeRayDriverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RayDriverServer will
// result in compilation errors.
type UnsafeRayDriverServer interface {
	mustEmbedUnimplementedRayDriverServer()
}

func RegisterRayDriverServer(s grpc.ServiceRegistrar, srv RayDriverServer) {
	s.RegisterService(&RayDriver_ServiceDesc, srv)
}

func _RayDriver_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RayDriverServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RayDriver_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RayDriverServer).ExecuteCommand(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RayDriver_ServiceDesc is the grpc.ServiceDesc for RayDriver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RayDriver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ray.RayDriver",
	HandlerType: (*RayDriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommand",
			Handler:    _RayDriver_ExecuteCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rayclient.proto",
}
