num_worker_nodes: 5
# simulating zero latency with some data throughput speed
simulated_delay: 0.0
node_ids:
  gcs: 0
  global_scheduler: 1
  ourself: 2
ports:
  local_object_store: 50000
  local_scheduler: 50001
  local_worker_start: 50002
  gcs_function_table: 50000
  gcs_object_table: 50001
  global_scheduler: 50000
dns:
  node_prefix: "node"
gcs:
  flush_interval_sec: 300 # put -1 to never flush
